// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {backend} from '../models';

export function GetDistros():Promise<Array<backend.WslDistro>>;

export function SaveSettings(arg1:string,arg2:Array<string>):Promise<void>;

export function ScanPaths(arg1:string):Promise<Array<backend.SelectableTool>>;
