// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetAutoStartStatus() {
  return window['go']['main']['App']['GetAutoStartStatus']();
}

export function GetDistros() {
  return window['go']['main']['App']['GetDistros']();
}

export function GetTraySetting() {
  return window['go']['main']['App']['GetTraySetting']();
}

export function SaveSettings(arg1, arg2) {
  return window['go']['main']['App']['SaveSettings'](arg1, arg2);
}

export function ScanPaths(arg1) {
  return window['go']['main']['App']['ScanPaths'](arg1);
}

export function ToggleAutoStart(arg1) {
  return window['go']['main']['App']['ToggleAutoStart'](arg1);
}

export function ToggleTraySetting(arg1) {
  return window['go']['main']['App']['ToggleTraySetting'](arg1);
}
