// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetDistros() {
  return window['go']['main']['App']['GetDistros']();
}

export function SaveSettings(arg1, arg2) {
  return window['go']['main']['App']['SaveSettings'](arg1, arg2);
}

export function ScanPaths(arg1) {
  return window['go']['main']['App']['ScanPaths'](arg1);
}
